---
- job:
    name: sf-docs-build
    description: Build the sf docs
    run: playbooks/build.yaml
    post-run: playbooks/publish.yaml
    success-url: 'docs-html/index.html'

- project:
    name: software-factory/sf-docs
    check:
      jobs:
        - sf-docs-build
